apiVersion: v1
kind: Secret
metadata:
  name: appsettings
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "carbon-aware-sdk.labels" . | nindent 4 }}
type: Opaque
stringData:
  appsettings.json: {{- .Values.appsettings | toYaml | indent 2 }}
