name: Generate Java client

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      spec-artifact:
        required: false
        type: string
        default: spec-artifact
      spec-filename:
        required: false
        type: string
        default: swagger.yaml

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Prepare
        run: |
          mkdir work doc
          npm install -g @openapitools/openapi-generator-cli@2.5.2
      - name: Download OpenAPI spec
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.spec-artifact }}
      - name: Generate client library
        # TODO: Update artifactUrl
        # TODO: Update registry URL in sed
        run: |
          echo '{"apiPackage": "foudation.greensoftware.carbonaware.webapi.client", "artifactDescription": "Carbon Aware SDK client library for Java", "artifactId": "casdk-client", "artifactVersion": "${{ inputs.version }}", "developerOrganization": "Green Software Foundation", "developerOrganizationUrl": "https://greensoftware.foundation/", "groupId": "foundation.greensoftware", "licenseName": "MIT License", "scmUrl": "https://github.com/Green-Software-Foundation/carbon-aware-sdk", "artifactUrl": "https://github.com/YaSuenag/carbon-aware-sdk/packages/", "scmConnection": "https://github.com/Green-Software-Foundation/carbon-aware-sdk.git", "scmDeveloperConnection": "https://github.com/Green-Software-Foundation/carbon-aware-sdk.git", "licenseUrl": "https://opensource.org/license/mit/", "developerName": "Green Software Foundation", "developerEmail": null}' > config.json
          openapi-generator-cli generate -i ${{ inputs.spec-filename }} -g java -o work -c config.json
          sed -i "s|</project>|<distributionManagement><repository><id>github</id><name>GitHub Packages</name><url>https://maven.pkg.github.com/YaSuenag/carbon-aware-sdk</url></repository></distributionManagement></project>|" work/pom.xml
        shell: bash
      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
      - name: Run Maven
        run: mvn -B -Dmaven.test.skip=true package javadoc:javadoc
        working-directory: work
      - name: Publish to GitHub Packages via Maven
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
        working-directory: work
      - name: Prepare to upload Javadoc
        run: mv work/target/apidocs doc/java
        shell: bash
      - name: Upload Javadoc
        uses: actions/upload-artifact@v3
        with:
          name: javadoc
          path: doc
